#debug: true
jg:
  server:
    graphs:
      ConfigurationManagementGraph: config/server/graph/jg_memory.properties
    scriptEngines:
      gremlin-groovy:
        plugins:
          "[org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin]":
            files:
              jg_memory: config/server/init-script/jg_configured_memory.groovy

