#debug: true
jg:
  server:
    graphs:
      tg_modern: config/server/graph/tg_modern.properties
    scriptEngines:
      gremlin-groovy:
        plugins:
          "[org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin]":
            files:
              tg_modern: config/server/init-script/tg_modern.groovy

