jg:
  server:
    host: localhost
    port: 8182
    evaluationTimeout: 30000
    channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
    graphs:
      graph: config/server/graph-config/jg_memory.properties
    scriptEngines:
      gremlin-groovy:
        plugins:
          "[org.apache.tinkerpop.gremlin.groovy.jsr223.GroovyCompilerGremlinPlugin]": {}
          "[org.janusgraph.graphdb.tinkerpop.plugin.JanusGraphGremlinPlugin]": {}
          "[org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin]": { }
          "[org.apache.tinkerpop.gremlin.tinkergraph.jsr223.TinkerGraphGremlinPlugin]": { }
          "[org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin]":
            classImports:
              math: java.lang.Math
            methodImports:
              math: java.lang.Math#*
          "[org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin]":
            files:
              graph: config/server/init-script/graph.groovy
    serializers:
      - className: org.apache.tinkerpop.gremlin.util.ser.GraphSONMessageSerializerV3
        config:
          ioRegistries:
            - org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerIoRegistryV3
      - className: org.apache.tinkerpop.gremlin.util.ser.GraphBinaryMessageSerializerV1
      - className: org.apache.tinkerpop.gremlin.util.ser.GraphBinaryMessageSerializerV1
        config:
          serializeResultToString: true                                                             # application/vnd.graphbinary-v1.0-stringd
    processors:
      - className: org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor
        config:
          sessionTimeout: 28800000
      - className: org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor
    metrics:
      consoleReporter:
        enabled: true
        interval: 180001
      csvReporter:
        enabled: true
        interval: 180000
        fileName: /tmp/gremlin-server-metrics.csv
      jmxReporter:
        enabled: false
      slf4jReporter:
        enabled: true
        interval: 180000
    strictTransactionManagement: false
    idleConnectionTimeout: 0
    keepAliveInterval: 0
    maxInitialLineLength: 4096
    maxHeaderSize: 8192
    maxChunkSize: 8192
    maxContentLength: 10485760
    maxAccumulationBufferComponents: 1024
    resultIterationBatchSize: 64
    writeBufferLowWaterMark: 32768
    writeBufferHighWaterMark: 65536
    ssl:
      enabled: false

grpc:
  server:
    port: 9090
    security:
      enabled: false
  client:
    test:
      address: static://localhost:9090
      negotiation-type: PLAINTEXT
